-- Insert common interests/skills
INSERT INTO interests (name, category) VALUES
  ('Web Development', 'Programming'),
  ('Mobile App Development', 'Programming'),
  ('Data Science', 'Programming'),
  ('Machine Learning', 'Programming'),
  ('Python', 'Programming'),
  ('JavaScript', 'Programming'),
  ('Java', 'Programming'),
  ('C++', 'Programming'),
  ('React', 'Programming'),
  ('Node.js', 'Programming'),
  ('Spanish', 'Languages'),
  ('French', 'Languages'),
  ('German', 'Languages'),
  ('Mandarin', 'Languages'),
  ('Japanese', 'Languages'),
  ('Guitar', 'Music'),
  ('Piano', 'Music'),
  ('Singing', 'Music'),
  ('Photography', 'Creative'),
  ('Video Editing', 'Creative'),
  ('Graphic Design', 'Creative'),
  ('Drawing', 'Creative'),
  ('Writing', 'Creative'),
  ('Public Speaking', 'Soft Skills'),
  ('Leadership', 'Soft Skills'),
  ('Time Management', 'Soft Skills'),
  ('Marketing', 'Business'),
  ('Finance', 'Business'),
  ('Accounting', 'Business'),
  ('Entrepreneurship', 'Business')
ON CONFLICT (name) DO NOTHING;
