-- Seed common interests based on Meet5 app patterns
INSERT INTO interests (name, category) VALUES
-- Outdoor
('Camping', 'outdoor'),
('Summer', 'outdoor'),
('Hiking', 'outdoor'),
('Autumn', 'outdoor'),
('Nature', 'outdoor'),
('Picnic', 'outdoor'),
('Spring', 'outdoor'),
('Garden', 'outdoor'),
('Beach', 'outdoor'),
('Winter', 'outdoor'),
('Walks', 'outdoor'),
('Gardening', 'outdoor'),
('Sea', 'outdoor'),
('Fishing', 'outdoor'),
('Forest', 'outdoor'),
('Sunbathing', 'outdoor'),
('Outdoor', 'outdoor'),
('Mountains', 'outdoor'),
-- Food & Drink
('Vegan', 'food'),
('Champagne', 'food'),
('Fries', 'food'),
('Vodka', 'food'),
('Sweets', 'food'),
('Cooking', 'food'),
('Bar', 'food'),
('Dining out', 'food'),
('Gin Tonic', 'food'),
('Wine', 'food'),
('Beer', 'food'),
('Vegetarian', 'food'),
('Ice cream', 'food'),
('Coffee', 'food'),
('Pizza', 'food'),
('Sushi', 'food')
ON CONFLICT (name) DO NOTHING;
